# Increments the persistent build counter and regenerates BuildInfo.h.
# Run as a script (cmake -P) from a pre-build step, with:
#   -DCOUNTER_FILE=<path to build_number.txt>
#   -DOUTPUT_HEADER=<path to generated BuildInfo.h>
#
# The counter file is the source of truth and is committed to the repo, so
# the build number is monotonic across machines/checkouts. Every compile
# bumps it by one and stamps the current build date/time into the header.

if(NOT DEFINED COUNTER_FILE OR NOT DEFINED OUTPUT_HEADER)
    message(FATAL_ERROR "increment_build.cmake: COUNTER_FILE and OUTPUT_HEADER required")
endif()

set(build_number 0)
if(EXISTS "${COUNTER_FILE}")
    file(READ "${COUNTER_FILE}" build_number)
    string(STRIP "${build_number}" build_number)
    if(NOT build_number MATCHES "^[0-9]+$")
        set(build_number 0)
    endif()
endif()

math(EXPR build_number "${build_number} + 1")
file(WRITE "${COUNTER_FILE}" "${build_number}\n")

string(TIMESTAMP build_date "%Y-%m-%d %H:%M")

# Only rewrite the header when its contents actually change, so downstream
# recompiles happen exactly once per bump.
set(header_body
"// Generated by cmake/increment_build.cmake — do not edit.
#pragma once
#define M2SUITE_BUILD_NUMBER ${build_number}
#define M2SUITE_BUILD_DATE \"${build_date}\"
")

set(existing "")
if(EXISTS "${OUTPUT_HEADER}")
    file(READ "${OUTPUT_HEADER}" existing)
endif()
if(NOT existing STREQUAL header_body)
    file(WRITE "${OUTPUT_HEADER}" "${header_body}")
endif()

message(STATUS "M2Suite build number: ${build_number} (${build_date})")
